import { FormFieldConfig } from './form-field.model';

export const COMPANIES_FORM: FormFieldConfig[] = [
  {
    name: 'name',
    label: 'Nombre',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '2',
    weight: 1,
    disabled: false,
    disabledOnEdit: true,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: '',
  },
  {
    name: 'legalRepresentative',
    label: 'Representante Legal',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '4',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: '',
  },
  {
    name: 'id',
    label: 'RUT/NIT',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    disabledOnEdit: true,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: '',
  },
  {
    name: 'address',
    label: 'Dirección',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: '',
  },
  {
    name: 'phone',
    label: 'Teléfono',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: 'num',
    pattern: '',
  },
  {
    name: 'email',
    label: 'Correo Electrónico',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
  },
  {
    name: 'logo',
    label: 'Logo',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: '',
  },
  {
    name: 'web',
    label: 'Sitio Web',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: undefined,
    pattern: '',
  },
    {
    name: 'isActive',
    label: 'Compañia activa',
    type: 'checkbox',
    show: true,
    required: true,
    value: false,
    maxLength: '',
    minLength: '',
    weight: 3,
    disabled: false,
    placeholder: '',
    pKeyFilter: undefined,
  },
];
