export const MODULE_FORM = [
  {
    name: 'name',
    label: 'Nombre',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: 'alpha',
    pattern: '',
  },
  {
    name: 'description',
    label: 'Descripción',
    type: 'textarea',
    show: true,
    required: true,
    value: '',
    maxLength: '300',
    minLength: '6',
    weight: 6,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'isActive',
    label: 'Rol activo',
    type: 'checkbox',
    show: true,
    required: true,
    value: false,
    maxLength: '',
    minLength: '',
    weight: 3,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
  },

];
