name: Deploy Angular app to Remote Server

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Angular app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # o la versión de Node que uses en tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build Angular production
        run: npm run build -- --configuration production

      - name: Prepare backup on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ -d /var/www/html/auth-module-backup ]; then
              rm -rf /var/www/html/auth-module-backup
            fi

            if [ -d /var/www/html/auth-module ]; then
              mv /var/www/html/auth-module /var/www/html/auth-module-backup
            fi

      - name: Copy build to remote server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/auth-module/browser/*"
          target: "/var/www/html/auth-module/"

      - name: Restart nginx on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart nginx

